import { useContext, useState, useEffect } from "react";
import { GlobalContext } from "utils/GlobalContext";
import { Link } from "react-router-dom";
import Helmet from "react-helmet";
import axios from "axios";

export default function Api() {
  const [darkMode, setDarkMode] = useContext(GlobalContext);
  const [fetched, setFetched] = useState(false)
  const [data, setData] = useState()

  async function getData() {
    try {
      const res = await axios.get('https://rickandmortyapi.com/api/location')
      if (res.status === 200) {
        setData(res.data.results)
        setFetched(true)
        console.table(res.data.results)
      }
    } catch (error) {
      console.log(error)
    }
  }

  useEffect(() => {
    if (!fetched) {
      getData();
    }
  }, [fetched])

  return (
    <>

      <Helmet>
        <title>Get Api Page</title>
        <meta name="description" content="Generated by create react app" />
      </Helmet>

      <main className="dark:bg-neutral-900 min-h-screen flex items-center justify-center flex-wrap">
        <div>

          <h1 className="mt-8 text-center text-4xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-3">
            Get Api Page
          </h1>

          <h1 className="text-4xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-3 text-center">
            <a href="https://reactjs.org/" className="text-sky-600 hover:text-sky-700 transition-all">React.js</a>
            {' '} + {' '}
            <a href="https://tailwindcss.com" className="text-cyan-600 hover:text-cyan-700 transition-all">Tailwind CSS</a>
          </h1>

          <div className="flex justify-center">
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </div>

          <div className="flex justify-center my-8 gap-x-4">
            <Link to="/" className="text-blue-500 hover:text-blue-600 transition-all font-medium">Home</Link>
            <Link to="/about" className="text-blue-500 hover:text-blue-600 transition-all font-medium">About</Link>
            <Link to="/users" className="text-blue-500 hover:text-blue-600 transition-all font-medium">Users</Link>
            <Link to="/api" className="text-blue-500 hover:text-blue-600 transition-all font-medium">Get API</Link>
          </div>

          <p className="dark:text-white my-4">Data from : {" "}
            <a href="https://rickandmortyapi.com/api/location" className="text-blue-500 hover:text-blue-600 transition-all" target="_blank" rel="noreferrer">
              https://rickandmortyapi.com/api/location
            </a>
          </p>

          {fetched ?
            <table className="mb-8">
              <thead>
                <tr className="py-2 border dark:border-neutral-700 dark:text-white font-medium">
                  <td className="px-4 py-2">ID</td>
                  <td className="px-4 py-2">Name</td>
                  <td className="px-4 py-2">Type</td>
                  <td className="px-4 py-2">Dimension</td>
                </tr>
              </thead>
              <tbody>
                {data.map(item => {
                  return (
                    <tr key={item.id} className="py-2 border dark:border-neutral-700 dark:text-gray-300">
                      <td className="px-4 py-2">{item.id}</td>
                      <td className="px-4 py-2">{item.name}</td>
                      <td className="px-4 py-2">{item.type}</td>
                      <td className="px-4 py-2">{item.dimension}</td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
            :
            <p className="dark:text-white">Loading...</p>
          }

        </div>
      </main>

    </>
  )
}
